# Generated by Django 3.2.7 on 2021-09-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subscribeemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribeemail',
            old_name='sbscrb_email',
            new_name='sbscrb',
        ),
    ]
